name: Deploy BlueOS Extension Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: "dronecan-gui"
          author: "Willian Galvani"
          author-email: "williangalvani@gmail.com"
